if AddJoke then
    AddJoke({
	"If you are being chased by a taxidermists, whatever you do, don't play dead",
	"I'm reading a book on anti-gravity. It's impossible to put down!",
	'Did you hear about the restaurant on the moon? Great food, no atmosphere!',
	'What do you call fake spaghetti? An impasta!',
	"Why don't scientists trust atoms? Because they make up everything!",
	'Why did the scarecrow win an award? Because he was outstanding in his field!',
	"I would tell you a construction joke, but I'm still working on it.",
	'What do you get when you cross a snowman and a vampire? Frostbite!',
	"I'm terrified of elevators, so I'm going to start taking steps to avoid them.",
	"Why don't skeletons fight each other? They don't have the guts.",
	'I told my wife she was drawing her eyebrows too high. She looked surprised.',
	"What do you call cheese that isn't yours? Nacho cheese!",
	"Why couldn't the bicycle stand up by itself? It was two-tired!",
	'What do you call a man with a rubber toe? Roberto!',
	'Why did the coffee file a police report? It got mugged!',
	"What's orange and sounds like a parrot? A carrot!",
	'I would avoid the sushi if I was you. Its a little fishy.',
	'To whoever stole my copy of Microsoft Office, I will find you. You have my Word!',
	"I'm reading a book about anti-gravity. It's impossible to put down!",
	"I would tell you a joke about an elevator but it's an uplifting experience.",
	"Why don't we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
	"Did you hear about the kidnapping at school? It's fine, he woke up!",
	'Why did the tomato turn red? Because it saw the salad dressing!',
	'What do you call an alligator in a vest? An investigator!',
	'What do you call a belt made of watches? A waist of time!',
	"I asked my dog what's two minus two. He said nothing.",
	'What do you call a factory that makes good products? A satisfactory.',
	"Why don't some couples go to the gym? Because some relationships don't work out!",
	'What do you call an elephant that doesnt matter? An irrelephant.',
	'Why do bees have sticky hair? Because they use honeycombs!',
	'What do you call a pile of cats? A meowtain!',
	'If you see a crime at an Apple Store, does that make you an iWitness?',
	"What's brown and sticky? A stick!",
	'How do you make a tissue dance? You put a little boogie in it!',
	"What do you call an elephant that doesn't matter? An irrelephant.",
	'What do you call a fish wearing a crown? A king carp!',
	"I'm on a whiskey diet. I've lost three days already.",
	'What do you call a fake noodle? An impasta!',
	'How does a penguin build its house? Igloos it together!',
	'What do you call a belt made out of watches? A waist of time.',
	'Did you hear about the fire at the circus? It was intense.',
	'Can February March? No, but April May!',
	"What's orange and sounds like a parrot? A carrot!",
	'What did the grape say when it got stepped on? Nothing but it let out a little wine!',
	'Why did the golfer bring two pairs of pants? In case he got a hole in one!',
	"I would tell a chemistry joke but I know I wouldn't get a reaction.",
	'Have you heard about the chocolate record player? It sounds pretty sweet.',
	'What do you call a deer with no eyes? No idea!',
	'I told my wife she was drawing her eyebrows too high. She looked surprised.',
	"Why don't skeletons fight each other? They don't have the guts.",
	'Why did the scarecrow win an award? Because he was outstanding in his field!',
	'Did you hear about the kidnapping at the playground? They woke up!',
	'What do you call a dog that can do magic? A Labracadabrador!',
	"Why can't you give Elsa a balloon? Because she will let it go!",
	'What do you call a pile of cats? A meowtain!',
	'Why did the bicycle fall over? Because it was two tired!',
	'What do you call a dinosaur with an extensive vocabulary? A thesaurus!',
	'What do you get from a pampered cow? Spoiled milk!',
	'Did you hear about the guy who invented Lifesavers? He made a mint!',
	'I used to play piano by ear, but now I use my hands.',
	"Why don't some couples go to the gym? Because some relationships don't work out!",
	'What does a lemon say when it answers the phone? Yellow!',
	'This graveyard looks overcrowded. People must be dying to get in.',
	"What do you call a boomerang that won't come back? A stick!",
	'Two antennas met on a roof, fell in love, and got married. The ceremony wasnt much, but the reception was excellent!',
	"Why don't scientists trust atoms? Because they make up everything!",
	'What do you call a snowman with a six-pack? An abdominal snowman.',
	'Why did the bicycle fall over? Because it was two-tired!',
	'How do you find Will Smith in the snow? You look for fresh prints.',
	"I'm only familiar with 25 letters in the English language. I don't know y.",
	'What do you call a factory that makes okay products? A satisfactory.',
	"If you're cold, stand in the corner. It's 90 degrees.",
	"What did the janitor say when he jumped out of the closet? 'Supplies!'",
	"Why don't skeletons fight each other? They don't have the guts.",
	"What did one wall say to the other wall? 'I'll meet you at the corner!'",
	"What do you call cheese that isn't yours? Nacho cheese!",
	'Why did the math book look sad? Because it had too many problems.',
	'What do you call a man with a rubber toe? Roberto.',
	"Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize!",
	'I used to play piano by ear, but now I use my hands.',
	'Why was the belt arrested? For holding up a pair of pants!',
	"Don't trust atoms; they make up everything!",
	'I would avoid the sushi if I were you. Its a little fishy.',
	"Want to hear a joke about construction? I'm still working on it.",
	"I wouldn't buy anything with velcro. It's a total rip-off!",
	'What do you get when you cross a snowman and a vampire? Frostbite.',
	"I'm reading a book on the history of glue. Can't put it down.",
	'Why did the scarecrow win an award? Because he was outstanding in his field!',
	"I'm terrified of elevators, so I'm going to start taking steps to avoid them.",
	'What do you call an alligator in a vest? An investigator!',
	'Why did the tomato turn red? Because it saw the salad dressing!',
	"What's orange and sounds like a parrot? A carrot!",
	'I told my wife she was drawing her eyebrows too high. She looked surprised.',
	"What's brown and sticky? A stick!",
	"Why don't skeletons fight each other? They don't have the guts.",
	'What do you call a bear with no teeth? A gummy bear!',
	'What do you call a pile of cats? A meowtain!',
	'What do you call a fish with two knees? A two-knee fish!',
	'Did you hear about the restaurant on the moon? Great food, no atmosphere!',
	'What do you call a can opener that doesnt work? A cant opener!',
	'What do you call a dog that can do magic? A Labracadabrador!',
	'What do you call a belt made of watches? A waist of time!',
	"I would tell you a joke about an elevator but it's an uplifting experience.",
	'How do you organize a space party? You planet.',
	'What do you call a singing Laptop? A Dell!',
	'Why was the computer cold? It left its Windows open!',
	'Why was the belt arrested? For holding up a pair of pants!',
	'What do you call a man who cant stand? Neil.',
	'Did you hear about the claustrophobic astronaut? He just needed a little space.',
	"Why don't oysters donate to charity? Because they are shellfish.",
	"Why don't skeletons fight each other? They don't have the guts.",
	'What do you call a dog that does magic tricks? A labracadabrador.',
	'What do you call a pile of cats? A meowtain!',
	'What do you call an alligator detective? An investi-gator.',
	"Why couldn't the bicycle stand up by itself? It was two-tired!",
	'What do you call a group of disorganized cats? A cat-astrophe!',
	"Why don't eggs tell jokes? They'd crack each other up.",
	"What do you call a boomerang that won't come back? A stick!",
	'Why did the scarecrow win an award? Because he was outstanding in his field!',
	'Why do bees have sticky hair? Because they use honeycombs.',
	'What do you get when you cross a snowman and a vampire? Frostbite.',
	"Why don't scientists trust atoms? Because they make up everything!",
	'What do you call a bear with no teeth? A gummy bear!',
	'Why did the golfer change his pants? Because he got a hole in one!',
	"What do you call a can opener that doesn't work? A can't opener!",
	'Why did the tomato turn red? Because it saw the salad dressing!',
	'What do you get when you cross a vampire and a snowman? Frostbite.',
	'How does a penguin build its house? Igloos it together!',
	"I'm reading a book on anti-gravity. It's impossible to put down!",
	"Want to hear a construction joke? Oh never mind, I'm still working on that one.",
	'What do you call a dinosaur with an extensive vocabulary? A thesaurus!',
	'What does a cloud wear under his raincoat? Thunderwear!',
	'Why was the math book sad? Because it had too many problems.',
	'What do you call a fake noodle? An Impasta!',
	'How do you make holy water? You boil the hell out of it.',
	"Why don't skeletons ever go trick or treating? Because they have no body to go with!",
	'What lies at the bottom of the ocean and twitches? A nervous wreck.',
	"Why don't scientists trust atoms? Because they make up everything!",
	'What do you call an academically successful slice of bread? An honor roll.',
	'How do you catch a squirrel? Climb up a tree and act like a nut!',
	'Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field!',
	'What do you call a parade of rabbits hopping backwards? A receding hare-line.',
	'What do you call an Argentinian with a rubber toe? Roberto.',
	"Why don't some fish play piano? Because you can't tuna fish!",
	'If a child refuses to nap, are they guilty of resisting a rest?',
	'What do you call a pile of cats? A meowtain!',
	'Why do melons have weddings? Because they cantaloupe!',
	'Did you hear about the circus fire? It was in tents.',
	"I'm reading a book about anti-gravity. It's impossible to put down!",
	'How many apples grow on a tree? All of them!',
	'Why did the golfer bring two pairs of pants? In case he got a hole in one!',
	'You know, people say they pick their nose, but I feel like I was just born with mine.',
	"What do you call an elephant that doesn't matter? An irrelephant!",
	'What do you get when you cross a snowman and a vampire? Frostbite!',
	"Why couldn't the bicycle stand up by itself? It was two tired.",
	'How do you make a Kleenex dance? Put a little boogie in it!',
	"I've got a great joke about construction, but I'm still working on it.",
	"What do you call cheese that isn't yours? Nacho cheese.",
	"Why don't skeletons fight each other? They don't have the guts.",
	'Why did the coffee file a police report? It got mugged.',
	'What has two butts and kills people? An assassin.',
	'The rotation of earth really makes my day.',
	"I thought about going on an all-almond diet. But that's just nuts.",
	"I've decided to sell my vacuum. It was just gathering dust!",
	"What's orange and sounds like a parrot? A carrot!",
	'I told my wife she was drawing her eyebrows too high. She looked surprised.',
	'My wife told me to stop impersonating a flamingo. I had to put my foot down.',
	'I would avoid the sushi if I were you. Its a little fishy.',
	'To the guy who invented Zero: Thanks for nothing!',
	'Whats E.T. short for? Because hes only got little legs.',
	'Why do crabs never give to charity? Because theyre shellfish.',
	"It's hard to explain puns to kleptomaniacs because they always take things literally.",
	'What do you call a man with a rubber toe? Roberto.',
	'Why did the bicycle fall over? It was two tired!',
	"What do you call a can opener that doesn't work? A can't opener!",
	'What do you call a dinosaur with a extensive vocabulary? A thesaurus!',
	'What do you get when you cross a snowman with a vampire? Frostbite.',
	"I'm reading a book on anti-gravity. It's impossible to put down!",
	"Why don't some couples go to the gym? Because some relationships don't work out!",
	'What do you call a donkey with only three legs? A wonkey.',
	'I used to hate facial hair, but then it grew on me.',
	"I'm terrified of elevators, so I'm going to start taking steps to avoid them.",
	'What do you call a boomerang that doesnt come back? A stick!',
	'Why did the math book look sad? Because it had too many problems.',
	'What do you call an alligator in a vest? An investigator!',
	'Where do beef burgers go to dance? The meatball.',
	"Why don't skeletons ever go trick or treating? Because they have no body to go with!",
	'What do you get when you cross a snowman with a vampire? Frostbite.',
	"I would tell you a chemistry joke but I know I wouldn't get a reaction.",
	'Whats Forrest Gumps password? 1forrest1.',
	"Why don't oysters share their pearls? Because they are shellfish.",
	'What did the janitor say when he jumped out of the closet? Supplies!',
	'Have you heard about the chocolate record player? It sounds pretty sweet.',
	'What do you call a fake noodle? An impasta!',
	'What do you call a factory that sells passable products? A satisfactory.',
	'Why did the bicycle fall over? Because it was two tired!',
	"I'm reading a book on the history of glue. I just can't seem to put it down.",
	"I'd tell you a Fibonacci joke, but it's probably as bad as the last two you've heard combined.",
	'What did the grape do when he got stepped on? Nothing but let out a little wine!',
	"Why do we tell actors to 'break a leg?' Because every play has a cast.",
	'Hear about the new restaurant called Karma? Theres no menu: You get what you deserve.',
	"A cheeseburger walks into a bar. The bartender says, 'Sorry, we dont serve food here.'",
	"I'm reading a book about anti-gravity. It's impossible to put down!",
	'I would tell you a UDP joke, but you might not get it.',
	"Two goldfish are in a tank. One says to the other, 'Do you know how to drive this thing?'",
	'I told my wife she was drawing her eyebrows too high. She looked surprised.',
	'What do you call a pile of kittens? A meowtain!',
	'Did you hear about the kidnapping at school? Its fine, he woke up!',
	"What's brown and sticky? A stick!",
	"Why couldn't the leopard play hide and seek? Because he was always spotted.",
	'What do you call a belt made out of watches? A waist of time!',
	"I would tell you a joke about an elevator but it's an uplifting experience.",
	"Why don't scientists trust atoms? Because they make up everything!",
	'What do you call someone with no body and no nose? Nobody knows.',
	"Why don't eggs tell secrets? They'd crack each other up!",
	"Did you hear the rumor about butter? Well, I'm not going to spread it!",
	"I only know 25 letters of the alphabet. I don't know y.",
	"Why don’t crabs give to charity? Because they’re shellfish.",
	"I used to be addicted to the hokey pokey… but I turned myself around.",
	"How do you find out how heavy a chili pepper is? Give it a weigh, give it a weigh, give it a weigh now.",
	"Did you hear the rumor about butter? Well, I'm not going to spread it!",
	"I’m so good at sleeping, I can do it with my eyes closed.",
	"Want to hear a joke about paper? Never mind, it’s tearable.",
	"What do you call two birds in love? Tweethearts.",
	"Why don’t eggs tell jokes? They’d crack each other up.",
	"What’s the best way to watch a fly fishing tournament? Live stream.",
	"Why don’t seagulls fly over the bay? Because then they’d be bagels.",
	"My dad told me a joke about boxing. I guess I missed the punchline.",
	"Why did the orange stop? It ran out of juice.",
	"What did the big flower say to the little flower? 'Hey, bud!'",
	"Why did the man fall down the well? Because he couldn’t see that well.",
	"I asked the gym instructor if he could teach me to do the splits. He replied, 'How flexible are you?' I said, 'I can't make it on Tuesdays.'",
	"I used to be a banker but I lost interest.",
	"Why did the chicken go to the séance? To talk to the other side.",
	"How do cows stay up to date? They read the moos-paper.",
	"I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did.",
	"Why did the scarecrow win an award? Because he was outstanding in his field!",
	"Why don't skeletons fight each other? They don't have the guts.",
	"Why did the bicycle fall over? Because it was two-tired!",
	"Why did the golfer bring two pairs of pants? In case he got a hole in one!",
	"Why don't scientists trust atoms? Because they make up everything!",
	"What do you call fake spaghetti? An impasta!",
	"Why did the coffee file a police report? It got mugged!",
	"What kind of shoes to frogs wear? Open-toad sandals.",
	"I just built an ATM that only gives out coins. I don’t know why no one’s thought of it before: it just makes cents!",
	"Did I ever tell you about the time I went mushroom foraging? It’s a story with a morel at the end.",
	"What happened when two slices of bread went on a date? It was loaf at first sight.",
	"Why do crabs never volunteer? Because they're shell-fish.",
	"I had a quiet game of tennis today. There was no racket.",
	"What's a shark's favorite saying? Man overboard!",
	"What did one slice of bread say to the other before the race? You're toast!",
	"I poured some water over a duck's back yesterday. I don't think he cared.",
	"How did I know my girlfriend thought I was invading her privacy? She wrote about it in her diary.",
	"Why did the electric car feel discriminated against? Because the rules weren't current.",
	"I'm such a good navigator, a self-driving car once asked me for directions.",
	"Why do melons have weddings? They cantelope.",
	"What did the bison say to his son when he left the ranch? Bi-son.",
	"Watch what you say around the egg whites. They can't take a yolk.",
	"I'm so good at fixing things, my motto is, If it is broke, I'll still fix it.",
	"Were did the pumpkins have their meeting? In the gourdroom.",
	"What's the best way to save your dad jokes? In a dadda-base.",
	"I got a new pen that can write under water. It can write other words too.",
	"My boss said “dress for the job you want, not for the job you have.” So I went in as Batman.",
	"I went to the aquarium this weekend, but I didn’t stay long. There’s something fishy about that place."
})
end
